# Sentiment Analysis

One of the trending topic was chosen on Twitter to perform sentiment analysis. For the purpose of this analysis, I've collected 1472 tweets. Based on the agreeement with Twitter to only read the tweets and do analysis for academic project, I won't be sharing the trending topic nor the content of the tweets.                            

The sentiment analysis was performed on a "word" level. I've attached 2 text files containing positive words and negative words. If the number of positive words in all of the tweets were more than the number of negative words, then I've concluded that the sentiment is positive. In order to further quantify if the sentiment is strongly positive or negative, 4 sentiment levels (strongly neative, moderately negative, moderately positive, strongly positive) were chosen.

In [1]:
# --------Print all the outputs in a cell--------
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### To extract text files and make a dictionary

2 text files of positive and negative words were converted into 2 lists each and then made into 1 dictionary.

Positive word list source: http://ptrckprry.com/course/ssd/data/positive-words.txt           
Negative word list source: http://ptrckprry.com/course/ssd/data/negative-words.txt           

; If you use this list, please cite one of the following two papers:
;
;   Minqing Hu and Bing Liu. "Mining and Summarizing Customer Reviews." 
;       Proceedings of the ACM SIGKDD International Conference on Knowledge 
;       Discovery and Data Mining (KDD-2004), Aug 22-25, 2004, Seattle, 
;       Washington, USA,                           
;   Bing Liu, Minqing Hu and Junsheng Cheng. "Opinion Observer: Analyzing 
;       and Comparing Opinions on the Web." Proceedings of the 14th 
;       International World Wide Web conference (WWW-2005), May 10-14, 
;       2005, Chiba, Japan.

In [2]:
# --------To read negative words from a text file and put it in a list--------
neg = [line.strip() for line in open('NegativeWords.txt', 'r')]
#print(neg)
# Prints list of negative words

In [3]:
# --------To read positive words from a text file and put it in a list--------
pos = [line.strip() for line in open('PositiveWords.txt', 'r')]
#print(pos)
# Prints list of positive words

In [4]:
# --------To make a single dictionary of positive and negative words.
d1 = {}                   
# Create an empty dictionary

for word in pos:            
    d1[word] = 1          
# Each positive word is a key in the dictionary and its value is assigned to be +1 using above for loop

for word in neg:
    d1[word] = -1         
# Each negative word is a key in the dictionary and its value is assigned to be -1 using above for loop

#print(d1)
# Prints dictionary of words as keys and values as +1 for positive word and -1 for negative word

### To extract text file containing tweets and save it as a list

In [5]:
# --------To pull out tweets from the text file and save it as a list--------
t = []
# Create an empty list

t = [word.lower().split() for word in open('tweets.txt', 'r', encoding = "utf-8")] 

#print(t)        
# Prints list of tweets by splitting each sentence into set of words.

### To calculate the overall sentiment:

In [6]:
pC = 0
# Create and initialize a variable to count number of positive words
nC = 0
# Create and initialize a variable to count number of negative words

for tweet in t:                                           # for every element in the list                                  
    for word in tweet:                                       # for every word in the element
        w1 = word.strip(' ’”"‘ !#@,./\_][ >:;&“》©$’?•')        # remove punctuations attached to each word
        if (w1 in d1.keys()):                                      # If clean word is present in the dictionary
            if (d1[w1] == 1):                                         # if it is a positive word
                pC += 1                                                  # increase the count of positive word
            elif (d1[w1] == -1):                                      # else
                nC += 1                                                  # increase the count of negative word
                
print("The total number of positive words is: " + str(pC))
# Prints: The total number of positive words is: 1653

print("The total number of negative words is: " + str(nC))
# Prints: The total number of negative words is: 887

print("The overall sentiment of the tweets in numeric value is: " + str(pC - nC))
# This gives the overall sentiment is nothing but the difference of positive and negative words which is (positive) 766.

The total number of positive words is: 1653
The total number of negative words is: 887
The overall sentiment of the tweets in numeric value is: 766


Note: We can also calculate the sentiment by creating a variable and initializing it to be zero and then adding 1 for every positive word and subtracting 1 for every negative word. But I have used 2 different counter variables in order to further quantify the overall sentiment.   

In [7]:
# --------To count the total number of tweets for analysis--------
tweetC = 0
# Initialize tweet counter variable to zero

for line in t:                      # for every element in list of tweets
    tweetC += 1                        # count the total number of elements  
        
print("The total number of tweets extracted were: " + str(tweetC))
# Prints: The total number of tweets extracted were: 1472

The total number of tweets extracted were: 1472


## Analysis

### Is the general sentiment positive or negative?
The total number of tweets extracted: 1472

The total number of positive words is: 1653.  
The total number of negative words is: 887.   
The overall sentiment of the tweets in numeric value is: 766.    
As the overall sentiment of the tweets is a positive number, we can say that the general sentiment is positive.


Also, the average number of positive words per tweet is: 1653/1472 = ~1.123. This means that on an average the number of positive words are more than 1 per tweet.     
The average number of negative words per tweet is 887/1472 = ~0.60. This means that on an average the number of negative words are 1 or none per tweet.







### Is the sentiment strongly or weakly positive?

Lets define the sentiment level into 4 parts:    
0 % - 25%: Strongly negative   
25% - 50%: Moderately negative   
50% - 75%: Moderately positive   
75% - 100%: Strongly positive   

The total number of positive and negative words 1653 + 887 = 2540  
As the sentiment is positive, the percentage of positive words: 1653/2540*100 = 65.08%    
As 65.08% lies in the 3rd part of our sentiment level, we can conclude that the overall sentiment is moderately positive.
